### PR TITLE
Support latest esprima implementation of rest parameters.

### PR DESCRIPTION
**Pull request by insidewhy**
The change makes it much easier to support!

### CODE REVIEW

**Comment by insidewhy** [comment]
You'll need the latest esprima harmony branch.

**Comment by matthewrobb** [comment]
We can't use the latest harmony branch yet. Since the pull for destructured parameters was accepted it would currently cause a major problem in the way destructuring currently desugars. I might be able to pull in the commit before the latest on there to get this pull in.

Right now I am working on the rewrite for Tree creation and hopefully by the end of the weekend we will be able to begin eliminating all string based rewriting and switch over to AST manipulation entirely.

**Comment by insidewhy** [comment]
Can we add a test for the case the new esprima breaks? All 24 tests
pass on this branch so I guess we're not covering the breakage.

**Comment by matthewrobb** [comment]
The test coverage is really low. I'm hoping that will also change very soon.

**Comment by insidewhy** [comment]
Cool, if you let me know what changed with this release that break the uncovered feature, then I can fix it and add a test!

**Comment by matthewrobb** [comment]
Currently ObjectPattern destructuring simply queries for ".ObjectPattern". This is a problem when you have ObjectPattern nodes in arguments.

``` JavaScript
function x({ y, z }) {  }
```

When it hits this it will try to treat it as if it's part of an assignment. It's going to need a special case in these instances. I worked quite a bit on the new-six branch stuff today. I have a first pass doing Egal rewriting using nothing but AST transforms. It also simplifies some things by beefing up the raw AST object rather than creating a node object that carries the AST. It's relying on non-enumerable properties and prototype inherited properties to make it possible to hand off this beefed up AST structure to escodegen. It's still pretty rough but I am excited about it. Hoping to iron it up and push the latest stuff to new-six branch tomorrow.

**Comment by matthewrobb** [comment]
In case you are interested, here's the first rough pass https://github.com/matthewrobb/six/blob/new-six-egal/src/rewriter.six#L37 

I think going this route is going to make life SO MUCH easier in the long run.

**Comment by insidewhy** [comment]
Much better.

**Comment by insidewhy** [comment]
With non-enumerable properties it won't work on IE8 and below I guess?

**Comment by insidewhy** [comment]
Could add in an extra pass for stupid slow ie8.. to remove the properties. Let decent JS environments avoid it using non-enumerables.

**Comment by matthewrobb** [comment]
Yeah, that can be done for sure. I'm not too concerned with having it capable of running in <IE9. Doing live compiling is going to be slower/worse either way.

**Comment by insidewhy** [comment]
I'm not either, but I guess some people might want that.

BTW the object pattern function parameters still hasn't landed in the latest ~~six~~ esprima, I think this pull request may be safe after all or did I miss something?

At any rate, since you're redoing everything no point; although the current state of six is still great for bootstrapping :)

**Pull request merged**
