### PR TITLE
Generated code in git differs when generating OS is Windows (carriage returns)

### PR DESCRIPTION
**Pull request by insidewhy**
I ran "sake compile:six" and it regenerated this file on Linux but without carriage returns.

### CODE REVIEW

**Comment by insidewhy** [comment]
Amended issue title and my comments to reflect real issue.

**Comment by insidewhy** [comment]
So this issue requires a second commit, either to add carriage returns from non-windows builds or remove them on windows builds.

**Comment by matthewrobb** [comment]
What would be best, in specific steps, to be done to prevent issues such as this moving forward. I develop on all three platforms and my gitconfig is generally defaulted to do it's line ending magic. I use Sublime Text 2 generally and can configure some things in there to deal with line endings.

**Comment by matthewrobb** [comment]
Closing this, fixed in a different commit.

**Pull request closed without merging**
