### PR TITLE
Support for module importing in nodjs.

### PR DESCRIPTION
**Pull request by insidewhy**
This pull request includes full support for importing and aliasing module members in node with three tests covering the cases.

Support for "export" and "module Id { ... } " will drop in the next pull request.

Cheers!

### CODE REVIEW

**Comment by matthewrobb** [comment]
I'm on my way out at the moment and haven't looked at the diffs but I just wanted to mention my intention to rewrite modules to UMD format in the long run.

**Comment by insidewhy** [comment]
Good idea, I'll update my patch to use UMD style with the node adapter from https://github.com/umdjs/umd/blob/master/nodeAdapter.js

**Comment by matthewrobb** [comment]
I would prefer https://github.com/umdjs/umd/blob/master/returnExports.js again in the long run. NodeAdapter is fine for now but If possible I'd like to not incur a performance hit with AMD, using the NodeAdapter UMD variant requires that the module get parsed for require calls.

**Comment by insidewhy** [comment]
I guess I disagree there, I don't mind the tiny bit of parsing done on startup to avoid the verbosity of that AMD requirement method.

I guess it's okay.

**Comment by insidewhy** [comment]
I mean.. in production you're probably going to pack all the files together as one anyway, it's probably only during development you'll use the separate AMD style modules anyway, and then the extra few microseconds won't hurt.

**Comment by matthewrobb** [comment]
I understand that point and agree however it won't be verbose in the source, it will be ES6 :)

**Comment by matthewrobb** [comment]
I say go with nodeAdapter for now either way. If it needs changed later it can be a discussion at that time.

**Comment by insidewhy** [comment]
Cool I'll let you know when I've updated my patch :) Changing it to use the returnExports method later will be a bit of work but hopefully not too much.

**Comment by insidewhy** [comment]
Okay updated the patch! The way it is structured supports UMD and also allows using ES Harmony statements and supports require/exports on node.js. I like it!

**Comment by matthewrobb** [comment]
I'm not sure I am following what's going on with the noModule bit?

**Comment by insidewhy** [comment]
"noModule" is used to not produce the outer "define" layer.

Mainly I'm just using this to get the tests to run as they use "eval" to put variables into the global scope and test them.

**Comment by insidewhy** [comment]
So if "noModule" is set then the function define wrapper isn't produced and then the AST contents doesn't need to be indented by one.

BTW I tested the modules produced by this patch using r.js from requirejs and they work fine.

**Comment by matthewrobb** [comment]
So it seems we should detect the use of any module-specific nodes and only if any are present do the wrapping?

**Comment by matthewrobb** [comment]
Also I am open to a more elegant method for running tests.

**Comment by insidewhy** [comment]
I think it's useful wrapping code in a define even when no modules are used.. that way when it is used in a web page then variables defined within source code won't pollute the global namespace? It's conceivable one file in a module system might not use any other modules (so no imports/exports) but you'd still want its contents hidden in a scope to allow it to be used in the same way as other files included within the module dependency tree.

**Comment by matthewrobb** [comment]
Very true.

**Comment by insidewhy** [comment]
Committed a bunch of cleanup and one fix. Have some further cleanups to make to test system but think that's probably better for a second patch.

**Comment by insidewhy** [comment]
Back to the topic of wrapping only when using module specific behaviour:

http://wiki.ecmascript.org/doku.php?id=harmony:modules_examples

The example at the bottom shows that each file implicitly becomes a module and must use "export" to make identifiers available. This seems to conflict with current ES behaviour of each file populating the global scope.

Is it the ES 6 intention to change something as fundamental as top-level scoping or have I missed something? The spec doesn't seem clear on this to me.

**Comment by matthewrobb** [comment]
I'm not entirely sure but I'd love to find out, can you ask about it in esdicuss?

**Comment by insidewhy** [comment]
Okay I amended the patch with some more simplifications and you can use the -g/--global command line flag to generate code in the global scope.

Please let me know if there's any more changes you'd like me to make. I'm keen to have this patch accepted as I have a few more features I want to add on top like support for "export".

**Comment by matthewrobb** [comment]
I will pull this and if all is good merge it tonight after work (EST)

**Comment by matthewrobb** [comment]
This is looking really good great job! Any way you can add something to the README to cover this?

**Comment by insidewhy** [comment]
Good point! I added it now let me know if there's anything you want me to change, or feel free to amend my language yourself!

**Comment by insidewhy** [comment]
Thank you!

**Comment by matthewrobb** [comment]
Hey, no, thank's for contributing. The state of the codebase is a bit embarrassing at the moment but I am hoping to have some time soon to devote to pushing it through. I've also gotten wind that Esprima Harmony may be supporting Default Prams, Rest, and Spread very shortly.

If you are planning on actively contributing we should chat about goals etc.

**Comment by insidewhy** [comment]
I was planning on adding a lot of stuff!

The source code isn't that bad although there's certainly a few complications I'd remove.

One thing I wondered is if we can use the source map support provided by escodegen. It looks however like we're reforming new code as a string and then building a new AST out of it which is then passed to generate. I guess we'd need to perform AST transforms directly (preserving the range objects) in order to get it and this would be pretty cumbersome.

We'd have to develop a system of making the AST transformations easier.

**Comment by matthewrobb** [comment]
I have a branch I was working on for that exact purpose. My goal is to make incremental transformations using escodegen rather than string-based rewriting. In fact my intention is to rewrite the entire tree system to be a lot more useful.

**Comment by matthewrobb** [comment]
I hacked this project together in very little time with the hope of making enough functional progress to keep moving on. I feel I succeeded but in the process the code is not up to par. I borrowed a lot from CoffeeScript etc just to get something in place.

**Comment by insidewhy** [comment]
My research is all about PEGs, AST construction and AST rewriting, I was hoping to implement my theories in JavaScript. Currently there's just C++11 and D implementations and it's getting ignored which is a shame because it's good work.

**Comment by matthewrobb** [comment]
https://github.com/Benvie/js-astify and https://github.com/Benvie/continuum are interesting projects playing with some of these ideas

**Pull request merged**
